In [1]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [2]:
import tensorflow as tf
import numpy as np

# 상수  : tf.constant()
s = tf.constant('Hello Tensorflow!!')
print(s)

a = tf.constant([[1.,2.],
                 [3.,4.]])
b = tf.constant([[1.,1.],
                 [0.,1.]])
c = tf.matmul(a,b)  # 내적 곱셈
print(c)
print(type(c))

tf.Tensor(b'Hello Tensorflow!!', shape=(), dtype=string)
tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
# 변수 : tf.Variable()
# 초기 값이 미리 설정,주로 텐서플로 내부에서 연산시 변경되는 변수에 사용,weight과 bias
a = tf.Variable(100)
b = tf.Variable(200)
c = tf.add(a,b)
print(c)

tf.Tensor(300, shape=(), dtype=int32)


### tf.Tensor: 텐서 객체
#### 텐서는 다차원 배열로 넘파이(NumPy) ndarray 객체와 비슷하며,
#### tf.Tensor 객체는 데이터 타입과 크기를 가지고 있다.
#### 또한 tf.Tensor는 GPU 같은 가속기 메모리에 상주할 수 있다.
#### 텐서플로는 텐서를 생성하고 이용하는 풍부한 연산 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등.)를 제공하며
#### 연산수행 시 자동으로 텐서를 파이썬 네이티브(native) 타입으로 변환하여 연산한다

In [4]:
# 연산자
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [5]:
# 속성과 타입 변환
a = tf.constant([[1.,2.],
                 [3.,4.]])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)

# Tensor객체를 ndarray로 변환
n = a.numpy()
print(n, type(n)) # <class 'numpy.ndarray'>

# 파이썬 native 타입으로 변환
a = tf.constant(10)
b = int(a)
print(b, type(b))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
10 <class 'int'>


In [6]:
a = 3.4
tf.cast(a,dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Logistic Regression : 2진 분류(Binary Classification)
: 2진 분류의 활성화 함수로는 sigmoid가 사용됨

In [7]:
tf.random.set_seed(5)

# 데이터 준비
# x_data : [6,2]
x_data = [[1,2],
          [2,3],
          [3,1],
          [4,3],
          [5,3],
          [6,2]]

# y_data : [6,1]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]
x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [8]:
# 변수 초기화 : weight, bias
# (m,n) * (n,l) = (m,l)   : 행렬의 내적 곱셈 공식
# (6,2) * (2,1) = (6,1)
W = tf.Variable(tf.random.normal([2,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
W

<tf.Variable 'weight:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627]], dtype=float32)>

In [9]:
# 예측 함수(hypothesis) : H(X) = sigmoid(W*X + b)
def hypothesis(X):
    return tf.sigmoid(tf.matmul(X,W) + b)

In [10]:
# 비용 함수 : logloss , 2진 분류 모델
def cost_func():
    # cost = tf.reduce_mean(tf.square(hypothesis(x_train) - y_train)) # 선형회귀모델
    
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) +
                         (1-y_train)*tf.math.log(1-hypothesis(x_train)))
    return cost    

In [11]:
# optimizer : 경사하강법
optimizer = tf.keras.optimizers.Adam(lr=0.01)

In [12]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    # cost를 minimize 한다
    optimizer.minimize(cost_func, var_list=[W,b])
    
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W:',W.numpy(),' b:',b.numpy())
print('***** Learning Finished!!')    

***** Start Learning!!
0000 cost:[ 1.6611367 ]  W: [[-0.17030667]
 [-0.9402863 ]]  b: [0.23652855]
1000 cost:[ 0.1793464 ]  W: [[1.3178084 ]
 [0.19723554]]  b: [-4.76143]
2000 cost:[ 0.07253333 ]  W: [[2.0121024 ]
 [0.84058464]]  b: [-8.711953]
3000 cost:[ 0.037006114 ]  W: [[2.6189134]
 [1.2299303]]  b: [-11.698347]
4000 cost:[ 0.020763222 ]  W: [[3.170924 ]
 [1.5396553]]  b: [-14.285827]
5000 cost:[ 0.012184971 ]  W: [[3.692799 ]
 [1.8153358]]  b: [-16.680555]
6000 cost:[ 0.0073189805 ]  W: [[4.197649 ]
 [2.0743647]]  b: [-18.973686]
7000 cost:[ 0.0044522793 ]  W: [[4.6926727]
 [2.3246498]]  b: [-21.210669]
8000 cost:[ 0.002727755 ]  W: [[5.1819434]
 [2.5701647]]  b: [-23.415749]
9000 cost:[ 0.0016780337 ]  W: [[5.667807]
 [2.812968]]  b: [-25.602285]
10000 cost:[ 0.001034765 ]  W: [[6.1516275]
 [3.0542433]]  b: [-27.777952]
***** Learning Finished!!


In [13]:
# Weight과 bias
print('Weight:',W.numpy())
print('Bias:',b.numpy())

Weight: [[6.1516275]
 [3.0542433]]
Bias: [-27.777952]


In [14]:
# 정확도 측정 : accuracy computation
def predict(X):
    return tf.cast(hypothesis(X) > 0.5,dtype=tf.float32)

# 학습 데이터를 그대로 검증 데이터로 사용하여 예측한 경우
x_test = x_train
y_test = y_train

preds = predict(x_test)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test),dtype=tf.float32))

print('Accuracy:',accuracy.numpy()) # Accuracy: 1.0
print('Hypothesis:\n',hypothesis(x_test).numpy())
print('Predict:\n',preds.numpy())

Accuracy: 1.0
Hypothesis:
 [[1.8225893e-07]
 [1.8111765e-03]
 [1.8908978e-03]
 [9.9750578e-01]
 [9.9999464e-01]
 [9.9999976e-01]]
Predict:
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


In [15]:
# 예측
print('***** Predict')
# x_data = [[1,2],
#           [2,3],
#           [3,1],
#           [4,3],
#           [5,3],
#           [6,2]]
x_data = [[1,1],
          [2,5],
          [3,3],
          [4,4],
          [5,2],
          [6,6]]
x_test = np.array(x_data,dtype=np.float32)
preds = predict(x_test)
print(preds.numpy())

***** Predict
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
