# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

#### https://greeksharifa.github.io/keras/2018/06/29/Keras-Tutorial/

### [1] Dense Layer

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# keras 를 이용한 XOR 네트워크

# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]   # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]     # (4,1)

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
# Dense Layer 구현
# tf.keras.layers.Dense(
#     units, activation=None, use_bias=True, kernel_initializer='glorot_uniform',
#     bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None,
#     activity_regularizer=None, kernel_constraint=None, bias_constraint=None,
#     **kwargs
# )
model = tf.keras.Sequential([
    # (4,2) * (2,10) = (4,10)
    # W : 2*10 = 20 , b : 10 ==> 학습 Parameter : 30
    tf.keras.layers.Dense(units=10, activation='sigmoid', input_shape=(2,)), # (None,10)
    
    # (4,2) * (10,1) = (4,1)
    # W : 10*1 = 10 , b : 1 ==> 학습 Parameter : 11
    tf.keras.layers.Dense(units=1, activation='sigmoid') # (None,1)   
])

model.summary() # # 각 layer의 정보를 출력

# 옵션 설정
model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.1), loss='binary_crossentropy',
             metrics=['accuracy'])

# loss 종류
# mean_squared_error :  평균제곱 오차
# binary_crossentropy : 이진분류 오차
# categorical_crossentropy : 다중 분류 오차

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                30        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [4]:
# 학습 수행
model.fit(x_train,y_train,epochs=100,batch_size=1,verbose=1)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 0.8719 - accuracy: 0.2500
Epoch 2/100
4/4 [==============================] - 0s 748us/step - loss: 0.7730 - accuracy: 0.5000
Epoch 3/100
4/4 [==============================] - 0s 747us/step - loss: 0.7509 - accuracy: 0.2500
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7199 - accuracy: 0.5000
Epoch 5/100
4/4 [==============================] - 0s 748us/step - loss: 0.7295 - accuracy: 0.5000
Epoch 6/100
4/4 [==============================] - 0s 756us/step - loss: 0.7525 - accuracy: 0.5000
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7289 - accuracy: 0.5000
Epoch 8/100
4/4 [==============================] - 0s 998us/step - loss: 0.7065 - accuracy: 0.5000
Epoch 9/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7418 - accuracy: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 1ms/step - loss: 0.7060 - accuracy: 0.5000
Epoch 11/100
4/4 [=

4/4 [==============================] - 0s 1ms/step - loss: 0.0423 - accuracy: 1.0000
Epoch 84/100
4/4 [==============================] - 0s 749us/step - loss: 0.0413 - accuracy: 1.0000
Epoch 85/100
4/4 [==============================] - 0s 748us/step - loss: 0.0391 - accuracy: 1.0000
Epoch 86/100
4/4 [==============================] - 0s 748us/step - loss: 0.0378 - accuracy: 1.0000
Epoch 87/100
4/4 [==============================] - 0s 748us/step - loss: 0.0361 - accuracy: 1.0000
Epoch 88/100
4/4 [==============================] - 0s 748us/step - loss: 0.0352 - accuracy: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 747us/step - loss: 0.0336 - accuracy: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 748us/step - loss: 0.0326 - accuracy: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 499us/step - loss: 0.0311 - accuracy: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 748us/step - loss: 0.0302 - accuracy: 1.0000
Epoch 93/100
4/

In [5]:
# 예측
preds = model.predict(x_train)
np.round(preds)

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [6]:
# 모델 평가 
model.evaluate(x_train,y_train)
# [0.022687405347824097, 1.0]

1/1 [==============================] - 0s 998us/step - loss: 0.0227 - accuracy: 1.0000


[0.022687405347824097, 1.0]

In [7]:
# X,Y input data 
x_train = np.array([[1.0,   2.0,  3.0,  4.0,  5.0],
                    [6.0,   7.0,  8.0,  9.0, 10.0],
                    [11.0, 12.0, 13.0, 14.0, 15.0]])  # (3,5)
                    
                    
y_train = np.array([[1.1,   2.2,  3.3,  4.4,  5.5],
                    [6.1,   7.2,  8.3,  9.4, 10.5],
                    [11.1, 12.2, 13.3, 14.4, 15.5]]) # (3,5)

model = tf.keras.Sequential([
    # (3,1) * (1,100) = (3,100)   , Param :200 (W:1*100, b:100), (1 + 1) * 100 = 200
    # tf.keras.layers.Dense(units=100, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 

    # (3,5) * (5,100) = (3,100)   , Param :600 (W:5*100, b:100), (5 + 1) * (100) = 600
    tf.keras.layers.Dense(units=100, activation='relu', input_shape=(5,)), # input data의 shape을 (?,5) 

    
    # (3,100) * (100,50) = (3,50)   , Param : 5050 (W:100*50, b:50), (100+1)*50 = 5050
    tf.keras.layers.Dense(units=50, activation='relu' ), 
    
    # (3,50) * (50,25) = (3,25)   , Param : 1275 (W:50*25, b:25), (50 + 1)* 25 = 1275
    tf.keras.layers.Dense(units=25, activation='relu' ),
    
    # (3,25) * (25,5) = (3,5)   , Param : 130 (W:25*5, b:5), (25 + 1) * 5 = 130
    tf.keras.layers.Dense(units=5 , activation='relu' ),
    
#     # (3,5) * (5,1) = (3,1)   , Pram : 6  (W:5*1, b:1), (5 + 1) *1 = 6
#     tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 100)               600       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 130       
Total params: 7,055
Trainable params: 7,055
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 997us/step - loss: 86.7635
Epoch 2/100
1/1 [==============================] - 0s 997us/step - loss: 69.8507
Epoch 3/100
1/1 [==============================] - 0s 995us/step - loss: 52.4968
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 40.9506
Epoch 5/100
1/1 [==============================] - 0s 998us/step - loss: 38.1061
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 38.0145
Epoch 7/100
1/1 [==============================] - 0s 995us/step - loss: 35.8517
Epoch 8/100
1/1 [==============================] - 0s 978us/step - loss: 33.6248
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 28.6726
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 22.6053
Epoch 11/100
1/1 [==============================] - 0s 997us/step - loss: 23.2542
Epoch 12/100
1/1 [==============================] - 0s 999us/step - loss: 25.3115
Epoch 13/100
1/1 [===============

In [9]:
model.predict(x_train)

array([[ 0.98594826,  0.        ,  3.3009012 ,  4.4354005 ,  5.4840903 ],
       [ 6.053206  ,  0.        ,  8.268296  ,  9.388879  , 10.451506  ],
       [11.146271  ,  0.        , 13.302449  , 14.4046    , 15.545564  ]],
      dtype=float32)

In [11]:
model.evaluate(x_train,y_train)

1/1 [==============================] - 0s 999us/step - loss: 13.7030


13.702960014343262

### [2] Flatten layer

In [12]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None, 28, 28, 10)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28*10) = (None,7840)

(1000, 28, 28, 10)
(1000, 7840)


In [13]:
# 3차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28).reshape(1000,28,28).astype(np.float32)
print(data.shape) # (None, 28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28) = (None,784)

(1000, 28, 28)
(1000, 784)


In [14]:
# 2차원 데이터는 그대로 2차원으로 FC Layer에 전달
data = np.arange(28*28).reshape(28,28).astype(np.float32)
print(data.shape) # (28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (28,28) 

(28, 28)
(28, 28)


### [3] Dropout Layer

In [15]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set to True automatically, and in other contexts, you can set 
# the kwarg explicitly to True when calling the layer.

# (This is in contrast to setting trainable=False for a Dropout layer.
# trainable does not affect the layer's behavior, as Dropout does not have any 
# variables/weights that can be frozen during training.)

In [30]:
# keras dropout

tf.random.set_seed(0)
data = np.arange(10).reshape(5,2).astype(np.float32)
print(data)

layer = tf.keras.layers.Dropout(0.3,input_shape=(2,))

outputs = layer(data,training=True)
# model.fit()호출 시는  학습 모드로 training=True가 되어 dropuout 적용
# model.evaluate() 호출 시는 예측 모드로 False가 되어 dropuout이 수행되지 않음
print(outputs) # 데이터의 30%는 0으로 나머지 데이터는  1/(1-0.3)으로 곱하여 scaled up된다
print(data*1/(1 - 0.3))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]


In [33]:
# 구버전 dropout : 사용이 번거로움
tf.random.set_seed(0)

data = np.arange(10).reshape(5,2).astype(np.float32)

def layer1(X,dr_rate):
    return tf.nn.dropout(X,rate=dr_rate)

layer1(data,dr_rate=0.3)   

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.       ,  0.       ],
       [ 2.857143 ,  4.285714 ],
       [ 5.714286 ,  7.1428576],
       [ 8.571428 , 10.       ],
       [11.428572 ,  0.       ]], dtype=float32)>