## Repeat 노드

In [1]:
import numpy as np

# 순전파
D = 8     # input_size 
N = 7     # 반복 횟수
x = np.random.rand(1,D)
print(x,x.shape)     # (1,8)

print('-'*70)

y = np.repeat(x,N,axis=0)  # 수직(행) 방향, axis=0
print(y,y.shape)

[[0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]] (1, 8)
----------------------------------------------------------------------
[[0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]
 [0.20174258 0.37835303 0.30633166 0.6411123  0.17698328 0.43437804
  0.01776169 0.94688621]] (7, 8)


In [2]:
# 역전파
dy = np.random.rand(N,D)
print(dy,dy.shape)  # (7,8)

print('-'*70)

dx = np.sum(dy,axis=0,keepdims=True) # 수직방향 합, keepdims=True이면 2차원, False면 1차원
print(dx,dx.shape)

[[0.13755782 0.07895582 0.33322873 0.47557111 0.73763113 0.91359252
  0.39951853 0.59419715]
 [0.94250455 0.49850586 0.25929771 0.74046384 0.93811118 0.06106741
  0.30435129 0.98298249]
 [0.92894598 0.11673657 0.89313594 0.8201634  0.82689308 0.56908959
  0.19176706 0.84401824]
 [0.82773417 0.81857911 0.24875482 0.98773671 0.32229478 0.48550033
  0.461513   0.80254745]
 [0.33065102 0.28933369 0.76789343 0.48299828 0.63632562 0.14548341
  0.68991635 0.10845651]
 [0.21040628 0.37244166 0.95776852 0.90652424 0.91714383 0.19002648
  0.28885493 0.25518524]
 [0.50075336 0.36642818 0.88227017 0.03829124 0.62787881 0.57162743
  0.22066506 0.61225651]] (7, 8)
----------------------------------------------------------------------
[[3.87855317 2.54098089 4.34234932 4.45174881 5.00627843 2.93638717
  2.55658622 4.19964359]] (1, 8)


In [3]:
a = np.array([[1,2,3,4]])
np.sum(a,keepdims=True)   # 2차원 유지

array([[10]])

### Sum 노드

In [4]:
# 순전파

D,N = 8, 7
x = np.random.randn(N,D)  # (7,8)
print(x,x.shape)

print('-'*70)

y = np.sum(x,axis=0,keepdims=True) 
print(y,y.shape)

[[ 0.86760038 -0.72147953 -0.95952631  0.54388987  0.51498001  0.39265621
   0.35977288  0.77732518]
 [ 0.21384386  0.21531284 -2.13145672  1.94585065 -2.05470305  0.06231518
  -0.28858813  0.18936996]
 [ 1.63380579  1.49716979 -0.80335148  0.50021132 -0.53103125  2.28788552
  -0.37840056 -2.30763407]
 [ 0.18690128 -0.27382036 -0.31372364  0.51348446 -0.66544056 -0.91383769
   0.12703328 -1.20981157]
 [ 0.46334813 -0.08154623 -0.35297035  0.69417144  0.616089    0.18513006
  -0.49205028  1.21562453]
 [-0.88387123  0.43094464 -1.61564678  0.30629645 -0.34789028  1.10066702
   0.1732179  -0.45423697]
 [-1.58133267  0.07304664 -0.73559451  1.26445401  0.25578512  0.03435073
  -0.41035099  0.42066144]] (7, 8)
----------------------------------------------------------------------
[[ 0.90029554  1.13962779 -6.91226978  5.7683582  -2.21221101  3.14916704
  -0.90936589 -1.36870151]] (1, 8)


In [5]:
# 역전파
D, N = 8, 7
dy = np.random.rand(1,D)
print(dy,dy.shape)     # (1,8)

print('-'*70)

dx = np.repeat(dy,N,axis=0)  # 수직(행) 방향, axis=0
print(dx,dx.shape)

[[0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]] (1, 8)
----------------------------------------------------------------------
[[0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]
 [0.15031319 0.65803608 0.70298368 0.51084182 0.70096724 0.27526445
  0.23301631 0.29596825]] (7, 8)


### Matmul 노드

In [12]:
class MatMul:
    def __init__(self,W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self,x):         # 순전파
        W, = self.params
        out = np.dot(x,W)
        self.x = x
        return out
    
    def backward(self,dout):     # 역전파
        W, = self.params
        dx = np.dot(dout,W.T)
        dW = np.dot(self.x.T,dout)
        self.grads[0][...] = dw    # 깊은 복사(deep copy)
        return dx        

In [15]:
# 얕은 복사
a = np.array([1,2,3])
b = np.array([4,5,6])
a = b
print(a)
id(a) == id(b)

[4 5 6]


True

In [16]:
# 깊은 복사
a = np.array([1,2,3])
b = np.array([4,5,6])
a[...] = b
print(a)
id(a) == id(b)

[4 5 6]


False

In [11]:
# np.zeros_like()
a = np.arange(12).reshape(3,4)
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 시그모이드 계층

In [17]:
class Sigmoid:
    def __init__(self):
        self.params,self.grads = [],[]
        self.out = None
        
    def forward(self,x): 
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self,dout):
        dx = dout * self.out *(1 - self.out)  # sigmoid함수의 미분: y*(1 - y), 공식 도출은 참고서적 참조
        return dx

## Affine 계층 : MatMul 노드에 bias를  더한 계층 

In [18]:
class Affine:
    def __init__(self,W,b):
        self.params = [W,b]
        self.grads = [np.zeors_like(W),np.zeros_like(b)]
        self.x = None
        
    def forward(self,x):
        W,b = self.params
        out = np.dot(x,W) + b
        self.x = x
        return out    
    
    def backward(self,dout):
        W,b = self.params
        dx = np.dot(dout,W.T)
        dW = np.dot(self.x.T,dout)
        db = np.sum(dout,axis=0)
        
        self.grads[0][...] = dw
        self.grads[1][...] = db
        return dx

## Softmax with Loss 계층

In [19]:
class SoftmaxWithLoss:
    def __init__(self):
        self.params,self.grads = [], []
        self.y = None    # softmax의 출력 값
        self.t = None    # 정답 레이블
        
    def softmax(self,x):
        if x.ndim == 2:
            x = x - x.max(axis=1, keepdims=True)
            x = np.exp(x)
            x /= x.sum(axis=1, keepdims=True)
        elif x.ndim == 1:
            x = x - np.max(x)
            x = np.exp(x) / np.sum(np.exp(x))
        return x 
    
    # https://smile2x.tistory.com/entry/softmax-crossentropy-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC 
    def cross_entropy_error(self,y, t):  
        if y.ndim == 1:
            t = t.reshape(1, t.size)
            y = y.reshape(1, y.size)

        # 정답 데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
        if t.size == y.size:
            t = t.argmax(axis=1)

        batch_size = y.shape[0]

        return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size  # 1e-7은 log(0)으로 무한대가 나오는걸 방지
          
    
    def forward(self, x, t):
        self.t = t
        self.y = self.softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = self.cross_entropy_error(self.y, self.t)
        return loss
     
    def backward(self,dout=1):
        batch_size = self.t.shape[0]

        # dx = (self.y - self.t)/batch_size # 순수 Softmax계층 일경우
        
        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size
        return dx

In [20]:
# softmax 구현시에  지수값이 크면 오버플로발생으로 nan이 나오는 것을 방지하기 위해 입력 값의 촤대값을 빼주어 사용한다
a = np.array([1010,1000,990])
print(np.exp(a))    # [inf inf inf]  , 무한대 값, 오버플로우 발생
x = np.exp(a)/np.sum(np.exp(a))
print(x)  # [nan nan nan]

c = np.max(a)
print(a - c)
x2 = np.exp(a - c)/np.sum(np.exp(a - c))
print(x2)  # [9.99954600e-01 4.53978686e-05 2.06106005e-09]

[inf inf inf]
[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


<ipython-input-20-b2248606c354>:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(a))    # [inf inf inf]  , 무한대 값, 오버플로우 발생
<ipython-input-20-b2248606c354>:4: RuntimeWarning: overflow encountered in exp
  x = np.exp(a)/np.sum(np.exp(a))
<ipython-input-20-b2248606c354>:4: RuntimeWarning: invalid value encountered in true_divide
  x = np.exp(a)/np.sum(np.exp(a))


## 가중치 갱신

In [21]:
# 확률적 경사하강법(Stochastic Gradient Descent)
class SGD:
    def __init__(self,lr=0.01):
        self.lr = lr     # learning rate,학습율
        
    def update(self,params,grads):
        for i in range(len(params)):
            params[i] -= self.lr*grad[i]

In [22]:
class Adam:
    '''
    Adam (http://arxiv.org/abs/1412.6980v8)
    
    '''
    def __init__(self, lr=0.001, beta1=0.9, beta2=0.999):
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.iter = 0
        self.m = None
        self.v = None
        
    def update(self, params, grads):
        if self.m is None:
            self.m, self.v = [], []
            for param in params:
                self.m.append(np.zeros_like(param))
                self.v.append(np.zeros_like(param))
        
        self.iter += 1
        lr_t = self.lr * np.sqrt(1.0 - self.beta2**self.iter) / (1.0 - self.beta1**self.iter)

        for i in range(len(params)):
            self.m[i] += (1 - self.beta1) * (grads[i] - self.m[i])
            self.v[i] += (1 - self.beta2) * (grads[i]**2 - self.v[i])
            
            params[i] -= lr_t * self.m[i] / (np.sqrt(self.v[i]) + 1e-7)
            
# https://dalpo0814.tistory.com/29