### 넘파이(NumPy) : 배열(ndarray, n dimension array)
* 리스트(list) : Linked List구조(불연속), 동작 속도가 느리다, comma로 요소구별, 서로 다른 자료형 사용가능 
* 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소 구별,오직 한 가지 타입만 갖을 수 있다 

https://www.scipy.org

In [1]:
import numpy as np
# ! pip install numpy

# list
list1 = [0,1,2,3,4,5,'hello']
print(list1)
print(type(list1))

a = np.array([0,1,2,3,4,5])
print(a)
print(type(a))  # ndarray
print(a.dtype)

[0, 1, 2, 3, 4, 5, 'hello']
<class 'list'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [2]:
# numpy 의 dtype 객체의 종류: 대소문자 모두 사용가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [3]:
# int와 float  ----> float
a = np.array([0,1,2.,3,4,5])
print(a)
print(type(a))
print(a.dtype)

[0. 1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [4]:
# int와 float 와 str --> Unicode String
a = np.array([0,1,2.,3,4,5,'Hello'])
print(a)
print(type(a))
print(a.dtype)  # <U32
# <U32 ,  < : 리틀엔디언, U:유니코드  , 32:최대문자 32 byte

# 유니코드 인코딩 방식
# (1) EUC-KR,CP949(MS949) : 완성형, 한글 2 바이트, 영문은 1 바이트, Windows
# (2) UTF-8 : 조합형, 한글 3 바이트, 영문은 1 바이트, Linux 

['0' '1' '2.0' '3' '4' '5' 'Hello']
<class 'numpy.ndarray'>
<U32


In [5]:
# 배열의 데이터 타입 변환 : astype()
a1 = np.array(['1.234','3.123','4.4356','5','7'])
print(a1, a1.dtype)

a2 = a1.astype('float32')
print(a2,a2.dtype)

a3 = a2.astype('int32')
print(a3,a3.dtype)

# a3 = a1.astype('int32') # ValueError

['1.234' '3.123' '4.4356' '5' '7'] <U6
[1.234  3.123  4.4356 5.     7.    ] float32
[1 3 4 5 7] int32


### 차원(dimension, Rank) 과 Shape
* 차원(Dimension, Rank) : 1,2,3 차원 , n 차원, 첫 데이터까지의 대괄호의 갯수
* Shape : 차원의 요소의 수, 튜플 형식
#### 1차원 Shape : (x,)
#### 2차원 Shape : (x,y)  , 행렬(matrix)
#### 3차원 Shape : (x,y,z) , (면,행,열)
...
#### n차원 Shape : (x,y,z,....)

In [6]:
# 1차원 배열의 Shape : (x,), 벡터
# np.arange(start,end+1,step)
a = np.arange(12)  # 0 ~ 11
print(a,type(a))
print(a.shape)  # (12,)
t = a.shape
print(type(t))
print(a.shape[0])


a2 = np.arange(2,10)
print(a2,type(a2))
print(a2.shape)

a3 = np.arange(0,16,2)
print(a3,a3.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
(12,)
<class 'tuple'>
12
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)
[ 0  2  4  6  8 10 12 14] (8,)


In [7]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis = 0) 과 열(column,세로,수평,axis =1)  ==> 필수 암기
m = np.array( [[0,1,2],
               [3,4,5]])
# m = np.array([np.arange(3),     
#               np.arange(3,6)])  # 동일한 결과
print(m)
print(m.shape)
print(m.shape[0],m.shape[1])

[[0 1 2]
 [3 4 5]]
(2, 3)
2 3


In [8]:
# 3차원 배열의 Shape : (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m)
print(m.shape)
print(m.shape[0],m.shape[1],m.shape[2])

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)
2 2 3


### 배열의 shape 바꾸기 : reshape() 함수

In [9]:
m1= np.arange(12)
print(m1,m1.shape)

m2 = m1.reshape(3,4)
print(m2,m2.shape)

m3 = m1.reshape(2,2,3)
print(m3,m3.shape)

m4 = m1.reshape(1,1,2,2,3,1)
print(m4,m4.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[[[[[ 0]
     [ 1]
     [ 2]]

    [[ 3]
     [ 4]
     [ 5]]]


   [[[ 6]
     [ 7]
     [ 8]]

    [[ 9]
     [10]
     [11]]]]]] (1, 1, 2, 2, 3, 1)


In [10]:
# -1 을 사용한 reshape : 자동으로 shape값을 계산
m1= np.arange(12)
m2 = m1.reshape(-1,6)
print(m2.shape)

m = np.arange(12).reshape(3,-1,2)
m.shape

(2, 6)


(3, 2, 2)

### 배열의 인덱싱과 슬라이싱

In [11]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법
d = np.arange(12)
print(d,d.shape)
print(d[0],d[1],d[2],d[-1])

print(d[2:8], d[:], d[:-1])
print(d[::2],d[::-1])

d[0] = 10
d

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 11
[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]


array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
# 2차원 배열의 인덱싱과 슬라이싱   : d[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)

# 인덱싱
print(d[0][0])  # 0
print(d[0,0])   # 0
print(d[2,1])

# 슬라이싱
print(d[0])   # [0 1 2 3]
print(d[0,:]) # [0 1 2 3], (4,), 1차원

print(d[:,:-1])    # (3,3), 마지막 열을 제외
print(d[::2,::2])  # (2,2)

# 요소변경 : 내부적으로 반복 수행을 통해 해당 데이터를 모두 변경
d[0,:] = 20   # 0번 행의 모든 요소를 20으로 변경
print(d)

d[::2,::3] = 30  # 슬라이싱 된 요소 전체를 한번에 변경할 수 있다
print(d)

d[:,:] = -1    # 전체 요소를 한번에 변경할 수 있다
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [13]:
# 3차원 배열의 인덱싱과 슬라이싱
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)
print(d[0][0][0])
print(d[0,0,0])     # 0

print(d[:,:-1,:-1]) # (2,1,2)
print(d[:,-1,:])    # (2,3)
print(d[:,-1,-1])   # (2,)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
[[[0 1]]

 [[6 7]]]
[[ 3  4  5]
 [ 9 10 11]]
[ 5 11]


### 불린 인덱싱: 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [14]:
a = np.array([1,2,3,4,5,6])
print(a)

print( a > 2 )  # [False False  True  True  True  True]
print(a[a > 2]) # 배열 a에서 2보다 큰 요소들을 추출

print(a[[False,False, True, True, True, True]]) # 동일한 결과

boolean_index = np.array([True,False,True,False,True,False]) # 리스트를 그대로 사용해도 가능
print(boolean_index)
print(a[boolean_index])

print(a[a!=3])
print(a[(a > 2) & (a < 6)])
print(a[(a % 2) == 0])
print(a[a < a.mean()])  # 배열 a에서 평균보다 작은 값만 추출

[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]
[3 4 5 6]
[ True False  True False  True False]
[1 3 5]
[1 2 4 5 6]
[3 4 5]
[2 4 6]
[1 2 3]


#### fancy 인덱싱 : 리스트나 배열로 임의의 집합을 지정하여 인덱싱,(멋대로 내키는 대로 인덱싱)

In [15]:
# 1 차원 배열의 fancy 인덱싱
a = np.arange(1,7)
print(a,a.shape)

print(a[[1,3,5,2]])
print(a[[0,-1,-3,-2]])

[1 2 3 4 5 6] (6,)
[2 4 6 3]
[1 6 4 5]


In [16]:
# 2 차원 배열의 fancy 인덱싱
a = np.arange(10,100,10).reshape(3,3)
print(a,a.shape)

print(a[[0,2],[0,1]])  # 행과 열이 서로 match
print(a[[0,2],:2])
print(a[0,0],a[2,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]] (3, 3)
[10 80]
[[10 20]
 [70 80]]
10 80


In [17]:
# 배열의 형상 다루기 : reshape(), 편평화(flatten()), 전치(transpose())

# flatten() : 다차원 배열을 1 차원으로 만든다
d = np.arange(12).reshape(3,4)
print(d)

f = d.flatten() # (3,4) --> (12,)  , d.reshape(12,)
print(f)

# 데이터 순서를 거꾸로 변경
print(d[::-1])      # 행의 순서를 거꾸로 변경
print(d[:,::-1])    # 열의 순서를 거꾸로 변경
print(d[::-1,::-1]) # 행과 열의 순서를 거꾸로 변경

# tranpose() : 전치 행렬, 행과 열을 서로 맞바꾸는 함수
t = d.transpose()
print(t)
print(t.shape)   # (3,4) --> (4,3)

print(d.T)       # transpose()와 동일한 결과

# 임시로 1차원으로 변경하여 데이터를 채우고 다시 원래의 shape을 갖는다
d.flat = 0
print(d,d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)


### numpy 의 속성(Attribute) : 멤버 변수, 메서드

#### dtype,shape,ndim,flat,T,size,nbytes

In [18]:
d = np.arange(12).reshape(3,4)
print(d.shape)
print(d.dtype)
print(d.ndim, len(d.shape))  # 2차원
print(d.T)   # 전치 행렬
print(d.nbytes) # 4 bytes * 12 ==> 48 bytess
print(d.size)  # 요소의 갯수
d.flat = 1
print(d)

(3, 4)
int32
2 2
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
48
12
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
# numpy 통계 함수들
a = np.arange(12).reshape(3,4)
print(a)

print(a.max())
print(a.min())
print(a.sum())
print(a.mean())

print(a.std())  # 표준편차
print(a.var())  # 분산
print(np.median(a)) # 중위수

# 사분위수
print('25%:',np.percentile(a,25)) # 1사분위수(Q1)
print('50%:',np.percentile(a,50)) # 2사분위수(Q2)  , median()과 같은 값
print('75%:',np.percentile(a,75)) # 3사분위수(Q3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
0
66
5.5
3.452052529534663
11.916666666666666
5.5
25%: 2.75
50%: 5.5
75%: 8.25


In [38]:
# axis 사용법
print(a)

print(a.sum())  # 배열 전체의 합

print(a.sum(axis = 0))     # 수직방향, 행방향
print(a.sum(axis = 1))     # 수평방향, 열방향

print(a.sum(axis = None))  #  a.sum()
print(a.sum(axis = -1))    # a.sum(axis = 1), -1: 마지막 축

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
66
[ 6 22 38]


In [42]:
# sort() 함수
a = np.array([9,2,8,3,1,4,5,6])
print(a,a.shape)

r = np.sort(a)  # 오름차순, 원본 변경 없음, sort된 결과를 반환
print(r)

a.sort()        # 오름차순, 원본 변경 
print(a)

r = np.sort(a)[::-1]  # 내림 차순: 오름 차순 정렬후 순서를 거꾸로 변경 
print(r)

[9 2 8 3 1 4 5 6] (8,)
[1 2 3 4 5 6 8 9]
[1 2 3 4 5 6 8 9]
[9 8 6 5 4 3 2 1]


In [44]:
# argsort() 함수 : sort된 후 해당 값의 인덱스(원본기준)를 반환
a = np.array([9,2,8,3,1,4,5,6])
print(a)
print(np.argsort(a))

[9 2 8 3 1 4 5 6]
[4 1 3 5 6 7 2 0]


### 배열 합치기
* 수직(v,행)으로 합치기 : vstack(), row_stack(), concatenate(..,axis=0)
* 수평(h,열)으로 합치기 : hstack(), column_stack(), concatenate(..,axis=1)

In [49]:
# 수직(v,행)으로 합치기
a = np.arange(9).reshape(3,3)
b = a * 2
print(a)
print(b)

r = np.vstack((a,b))  # 수직
print(r,r.shape)

c = np.row_stack((a,b)) # 행
print(c,c.shape)

x = np.concatenate((a,b),axis=0)  # axis = 0 , 행, 수직
print(x,x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [51]:
# 수평(h,열)으로 합치기
a = np.arange(9).reshape(3,3)
b = a * 2
print(a)
print(b)

r = np.hstack((a,b))  # 수평
print(r,r.shape)

c = np.column_stack((a,b)) # 열
print(c,c.shape)

x = np.concatenate((a,b),axis=1)  # axis = 1 , 열, 수평
print(x,x.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


### 쪼개기
* vsplit(배열,행의 갯수) : 수직, split(배열,행의 갯수,axis = 0)
* hsplit(배열,열의 갯수) : 수평, split(배열,행의 갯수,axis = 1)

In [61]:
a = np.arange(12).reshape(4,3)
print(a)

# 수직방향
print(np.vsplit(a,4))
print(np.split(a,4,axis=0))

a = np.arange(12).reshape(3,4)
print(a)

# 수평방향
print(np.hsplit(a,4))
print(np.split(a,4,axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


### 배열의 연산: 행렬(matrix)의 연산, 선형대수(Linear Algebra)

### [1] 배열과 상수간의 연산 :  배열 <연산자> 상수, 상수 <연산자> 배열
#### 하나의 스칼라와 배열의 연산, 브로드 캐스팅에 해당

In [73]:
A = np.arange(16).reshape(4,4) 
print(A,A.shape)

print(A + 10)
print(A - 10)
print(A * 10)
print(A / 10)
print('-'*30)
print(10 + A)
print(10 - A)
print(10 * A)
print(10 / (A  + 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5]]
------------------------------
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[10  9  8  7]
 [ 6  5  4  3]
 [ 2  1  0 -1]
 [-2 -3 -4 -5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[10.          5.          3.33333333  2.5       ]
 [ 2.          1.66666667  1.42857143  1.25      ]
 [ 1.11111111  1.          0.90909091  0.83333333]
 [ 0.76923077  0.71428571  0.66666667  0.625     ]]


In [78]:
# 나누기
print(np.divide(10,0)) # inf
print(np.divide(0,0))  # nan , not a number

print(np.log(0)) # -inf
print(np.log1p(0)) # np.log(1)

inf
nan
-inf
0.0


<ipython-input-78-7c65d594619d>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(10,0)) # inf
<ipython-input-78-7c65d594619d>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(0,0))  # nan , not a number
<ipython-input-78-7c65d594619d>:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(0)) # -inf


### [2] element-wise 연산 : 배열과 배열의 요소간의 연산

In [82]:
# shape 이 같은 경우
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3) - 1
print(A)
print(B)

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  1  3]
 [ 5  7  9]
 [11 13 15]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]
[[-0.                 inf  2.        ]
 [ 1.5         1.33333333  1.25      ]
 [ 1.2         1.16666667  1.14285714]]


<ipython-input-82-ad5484412bf8>:10: RuntimeWarning: divide by zero encountered in true_divide
  print(A / B)


### 브로드 캐스팅 : 차원의 크기가 서로 다른 배열에서 산술연산이 가능

In [85]:
A = np.arange(6).reshape(3,2)
B = np.arange(2).reshape(1,2) + 1
print(A)     # (3,2)
print(B)     # (1,2)

print('-'*30)
print(A + B)
print(A - B)
print(A * B)
print(A / B)

print('-'*30)
print(B + A)
print(B - A)
print(B * A)
print(B / A)

[[0 1]
 [2 3]
 [4 5]]
[[1 2]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[-1 -1]
 [ 1  1]
 [ 3  3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[0.  0.5]
 [2.  1.5]
 [4.  2.5]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[ 1  1]
 [-1 -1]
 [-3 -3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[       inf 2.        ]
 [0.5        0.66666667]
 [0.25       0.4       ]]


<ipython-input-85-8f877756fe63>:16: RuntimeWarning: divide by zero encountered in true_divide
  print(B / A)


In [87]:
# 브로드 캐스팅 규칙 : 차원과 shape 이 자동 조정
# 규칙 1 : 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열의 shape의
#          앞쪽(왼쪽)을 1로 채운다
# 규칙 2 : 차원이 같은 두 배열의 shape 이 1인 배열을 다른 배열의 shape과 
#          일치하도록 늘인다
# 규칙 3 : 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생

A = np.ones((2,3))  # (2,3)
B = np.arange(3)    # (3,)
print(A)
print(B)

# 규칙 1 적용 :  B.shape ==> (1,3)      [[0 1 2]]
# 규칙 2 적용 :  B.shape ==> (2,3)      [[0 1 2]
#                                        [0 1 2]]
print(A + B)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [89]:
A = np.ones((3,1))  # (3,1)
B = np.arange(3)    # (3,)
print(A)
print(B)

# 규칙 1 적용 :  B.shape ==> (1,3)      [[0 1 2]]
# 규칙 2 적용 :  B.shape ==> (3,3)      [[0 1 2]
#                                        [0 1 2]
#                                        [0 1 2]]
# 규칙 2 적용 :  A.shape ==> (3,3)      [[1. 1. 1.]
#                                        [1. 1. 1.]
#                                        [1. 1. 1.]]

print(A + B)

[[1.]
 [1.]
 [1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [91]:
A = np.ones((3,2))  # (3,2)
B = np.arange(3)    # (3,)
print(A)
print(B)

# 규칙 1 적용 :  B.shape ==> (1,3)      [[0 1 2]]
# 규칙 2 적용 :  B.shape ==> (3,3)      [[0 1 2]
#                                        [0 1 2]
#                                        [0 1 2]]
# 규칙 3 에 해당하므로 오류 발생
# print(A + B)  # ValueError

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [ ]:
# 끝쪽 차원부터 비교하면서 앞쪽으로 진행한다
# 두 배열의 각 차원에서 shape 이 같거나 shape이 1인경우 브로드캐스팅 가능
A  =  (2, 3)
B  =     (3,)
---------------
결과: (2, 3)  
    
A  =  (3, 1)
B  =     (3,)
---------------
결과: (3, 3) 
    
A  =  (3, 2)
B  =     (3,)
---------------
결과: (3, x)   ===> 오류
    
A  =  (15, 3, 5)
B  =      (3, 1)
-----------------
결과: (15, 3, 5 ) 
    
A  =  (8, 1, 6, 1)
B  =     (7, 1, 5)
--------------------    
결과: (8, 7, 6, 5) 
    
A  =  (8, 4, 3)
B  =     (2, 1)
--------------------
결과: (8, x, 3) ==> 오류  

### [3] dot product: 내적(inner) 곱 ,행렬(matrix)¶

In [95]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape,b.shape)

print(a * b)         # element-wise 곱셈
print(np.dot(a,b))   # 내적 곱
print(a[0]*b[0] + a[1]*b[1] + a[2]*b[2])  # 벡터의 내적 : 요소의 곱의 합

(3,) (3,)
[ 4 10 18]
32
32


In [101]:
# 행렬의 곱셈 : np.dot()
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)
print(A)    # (2,3)
print(B)    # (3,2)
# A*B : element-wise 곱셈은 오류 발생, shape이 다르고 1도 아님

dot_product = np.dot(A,B)
print(dot_product,dot_product.shape) # (2,2)

# (2,3) * (3,2) = (2,2)
# (m,n) * (n,l) = (m,l)   # 행렬의 내적 곱셈 shape 공식, 필수 암기 요망!!

# (10,4) * (x,y) = (10,2) # x = 4, y = 2 를 구할 수 있어야한다

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]] (2, 2)


In [102]:
np.matmul(A,B)  # 동일한 결과, 2차원(행렬)만 사용 가능

array([[ 58,  64],
       [139, 154]])

In [105]:
A = np.mat("1 2 3;4 5 6")
B = np.mat("7 8;9 10;11 12")
print(A)    # (2,3)
print(B)    # (3,2)
print(type(A))  # <class 'numpy.matrix'>

print(A * B) # dot (내적 곱셈) 연산
# (2,3) * (3,2) = (2,2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
<class 'numpy.matrix'>
[[ 58  64]
 [139 154]]


In [109]:
# 기타 연산자: np.zeros(), np.ones()
z = np.zeros(10)
print(z)

z = np.zeros((3,4))
print(z)

o = np.ones(10)
print(o)

o = np.zeros((3,4))
print(o)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [115]:
# np.empty() 함수
e = np.empty((3,5))  # 초기 값을 초기화 하지 않고 바로 배열을 생성, 대용량을 고속으로 할당
print(e)             # 초기 값이 garbage(쓰레기)값이 그대로 유진된 상태에서 배열이 생성

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]]
