In [3]:
import numpy as np


#shape 는 길이를 리턴해줌 튜플형태로 , 이 찍히게 나옴
a= np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [4]:
b= np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [7]:
a=np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,2),7)
print(c)

d=np.eye(2)
print(d)

e=np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.53521095 0.29566009]
 [0.58384807 0.16154869]]


In [13]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b=a[:2,1:3]

print(b)

#포인터 인갑ek
print(a[0,1])
b[0,0]=77
print(a[0,1])

[[2 3]
 [6 7]]
2
77


In [11]:
print(b)
print([b[:]])

[[77  3]
 [ 6  7]]
[array([[77,  3],
       [ 6,  7]])]


In [18]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#들고오는 값은 같지만 대괄호가 붙음
row_r1 = a[1,:]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
a = np.array([[1, 2], [3, 4], [5, 6]])


# [1 4 5] 1차원 행렬(3,)을 얻는 두 가지 방법

print(a[[0, 1, 2], [0, 1, 0]])
print(a.shape)
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


[1 4 5]
(3, 2)
[1 4 5]
(2, 2)


In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # [1 6 7 11]



#이건왜 b번째에 연산을 하는거지?
#데이터 타입이 지금 int라서 int형 으로 만 계산 가능 / 나누기도 안되네 ; 
a[np.arange(4), b] += 10
print(a)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [34]:
x=np.array([1,2])
print(x.dtype)

x=np.array([1.0, 2.0])
print(x.dtype)

x=np.array([1,2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [35]:
x=np.array([[1,2],[3,4]], dtype = np.float64)
y=np.array([[5,6],[7,8]], dtype = np.float64)

print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [37]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

#내적값 계산
print(v.dot(w))
print(np.dot(v,w))

#매트릭스 / 벡터 곱 ; [29 67]
print(x.dot(v))
print(np.dot(x,v))

# 매트릭스 / 매트릭스 곱;
# [[19 22] [43 50]]
print(x.dot(y))
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [38]:
x = np.array([[1,2],[3,4]])

#행의 값 더하기 열의 값 더하기 
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [42]:
a= np.ones((2,3,4))
print(np.sum(a, axis=1))

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [43]:
#전치 행렬
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [44]:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


In [47]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y= np.empty_like(x)

for i in range(4): #range(4) = x.shape[0]
    y[i, :] = x[i, :]+v

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복

print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [51]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [61]:
# 연습 문제2 / 연립차 방정식 풀가
x= np.array([[1,1],[2,1]])
y=np.array([15, 25])
x_inv = np.linalg.inv(x)


a=np.array(np.dot(x_inv,y))
print(a)





[10.  5.]


In [148]:
def and_op(x):
    w=np.array([[2,2],[5,5]])
    
    b=np.array([4,0])
    
    tmp=np.zeros(2)
    
    a=np.dot(w,x)
    tmp=a+b
    print(tmp)
    return np.argmax(tmp)
    

x1=np.array([0,0])
and_op(x1)
    
    

[4 0]


0

In [82]:
and_x=np.ones([2,2])
print(len(and_x))

2


In [94]:
0 and 0

0

In [104]:
tmp=np.zeros(2)
tmp

array([0., 0.])

In [116]:
sorted(np.array([1,2,3,6,4,3]))

[1, 2, 3, 3, 4, 6]